name: qc_hik_player
description: Flutter plugin for HikIot live stream player on Android.
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.qc.qc_hik_player
        pluginClass: QcHikPlayerPlugin

dependencies:
  flutter:
    sdk: flutter

